*&---------------------------------------------------------------------*
*& Include YCL122_002_TOP                           - Module Pool      YCL122_002
*&---------------------------------------------------------------------*
PROGRAM YCL122_002.

TABLES SCARR.
DATA : OK_CODE TYPE SY-UCOMM,
       SAVE_OK(20) TYPE C .

DATA : GT_SCARR TYPE TABLE OF SCARR.

SELECTION-SCREEN BEGIN OF SCREEN 0101 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(10) TEXT-L02 FOR FIELD S_CARRID.
   SELECT-OPTIONS S_CARRID FOR SCARR-CARRID.
   SELECTION-SCREEN END OF LINE.

   SELECTION-SCREEN BEGIN OF LINE.
     SELECTION-SCREEN COMMENT 1(10) TEXT-L03 FOR FIELD S_CARRNM.
     SELECT-OPTIONS S_CARRNM FOR SCARR-CARRNAME.
   SELECTION-SCREEN END OF LINE.

*   SELECTION-SCREEN SKIP 1.   " SELECTION-SCREEN * LINE을 사용했기 때문에 쓰지 않아도 된다.
   SELECTION-SCREEN PUSHBUTTON 57(3) TEXT-L01 USER-COMMAND SEARCH.

   SELECTION-SCREEN END OF BLOCK B01.
  SELECTION-SCREEN END OF SCREEN 0101.
