*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_SQL_S
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_A22_STOP.
*INCLUDE BC414_TRAVELAG_SQL_STOP.
INCLUDE ZTRAVELAG_A22_SF01.
*INCLUDE BC414_TRAVELAG_SQL_SF01.
INCLUDE ZTRAVELAG_A22_SO01.
*INCLUDE BC414_TRAVELAG_SQL_SO01.
INCLUDE ZTRAVELAG_A22_SI01.
*INCLUDE BC414_TRAVELAG_SQL_SI01.
INCLUDE ZTRAVELAG_A22_SE01.
*INCLUDE BC414_TRAVELAG_SQL_SE01.
